### ISSUE TITLE
pyi mode: line length to 130

### ISSUE THREAD

**Issue by JelleZijlstra** [python/black#341]
Typeshed's style guidelines now recommend a 130-character line length (https://github.com/python/typeshed/commit/da7b04904c3000f137f9b2559f9bb55b28d0a3b7). Should Black use the same line length for pyi files?

A complication: If Black is formatting both `.py` and `.pyi` files in a single run, what should the behavior of the `--line-length` command-line flag be? Perhaps we should add a separate `--pyi-line-length` flag, or just say that you shouldn't use a custom line length if you want to format both kinds of files within the same invocation of Black.

**Comment by ambv** [comment]
I don't want another command-line option. What I would do instead is:
- if the user doesn't provide a value via `--line-length=` it would do the dynamic 130 for .pyi and 88 for everything else;
- if the user provided `--line-length=`, it's used everywhere.

**Comment by ambv** [comment]
But in general, I have to think whether this is something we need to adopt in Black at all. Running Black with `-l 130` today on a bunch of .pyi files will do the correct thing, too, after all.

What do you think? Why should Black conform to the typeshed style?

**Comment by JelleZijlstra** [comment]
I think typeshed's style is the de facto standard for stub style in general, so just as Black tries to follow PEP 8 for non-stub style, it should try to follow typeshed's style for stubs.

But I don't feel strongly about this, and in this particular case it's easy enough to just manually pass in `-l 130`. It's up to you.

**Comment by ambv** [comment]
With an automatic formatter the rule to keep the pyi files at 130 characters per line seems odd to me. Wide lines are usually motivated by two things:
- saving time otherwise needed for hand-reformatting when a line gets too long;
- being able to see more structure in one screen.

With Black, only the latter applies now (barring us breaking type comments currently which we'll address soon). So to help me make an informed decision, I will need to see how often in typeshed we are placing lines longer than 88. In other words, would the special rule provide a big quality of life difference or maybe it doesn't actually matter much.
