### ISSUE TITLE
Flake8-commas support

### ISSUE THREAD

**Issue by yutkin** [python/black#551]
Is there any plans to conform [flake8-commas](https://github.com/PyCQA/flake8-commas)?

**Comment by JelleZijlstra** [comment]
I'm not familiar with this tool, but glancing at the README it should mostly already match Black's behavior. What specific change are you looking for?

**Comment by yutkin** [comment]
After black usage, I still have several warnings from flake8-commas (C812, C815, C816).
For example, line 546 causes C812 warning.
```
545     fill_data = missing_values_filling_needed(
546         get_filters(report_query.get("metrics", []))
547     )
```

**Comment by asottile** [comment]
I think the idea with black is that you'd remove `flake8-commas` because `black` will automatically rewrite your code to avoid the things it _would_ lint for.

The one disagreement between the two tools is that `black` will not put a comma on single line calls (an aside: this is also the only inconsistency between black and [add-trailing-comma](https://github.com/asottile/add-trailing-comma))

**Comment by JelleZijlstra** [comment]
Doesn't sound like this is currently actionable.
